"""add ratings table again

Revision ID: b6cefb3ff151
Revises: 675333cdd594
Create Date: 2026-03-03 08:43:43.131431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6cefb3ff151'
down_revision: Union[str, Sequence[str], None] = '675333cdd594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('imdb', sa.String(), nullable=True),
    sa.Column('rt', sa.String(), nullable=True),
    sa.Column('serializd', sa.String(), nullable=True),
    sa.Column('ai_sent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('ratings')
    # ### end Alembic commands ###
